In [1]:
import torch

In [7]:
x = torch.randn(3, 2, 2)
print(x)
y = torch.ones(3, 1).unsqueeze(-1).repeat(1, 2, 2)
print(x*y)

tensor([[[ 0.0421,  0.7913],
         [ 0.9218,  0.8418]],

        [[ 0.8133,  0.1313],
         [-0.3978,  1.1270]],

        [[ 0.8449, -0.6964],
         [-0.5147,  0.9430]]])
tensor([[[ 0.0421,  0.7913],
         [ 0.9218,  0.8418]],

        [[ 0.8133,  0.1313],
         [-0.3978,  1.1270]],

        [[ 0.8449, -0.6964],
         [-0.5147,  0.9430]]])


In [4]:
# h x t
num_time_steps = torch.tensor(5)
num_basis_coefficients = torch.tensor(4)
dct_basis_function_matrix = torch.zeros([num_time_steps, num_basis_coefficients])
for time_step_index in range(num_time_steps):
    for basis_coefficient_index in range(num_basis_coefficients):
        dct_basis_function_matrix[
            time_step_index, basis_coefficient_index
        ] = torch.sqrt(2.0 / num_time_steps) * torch.cos(
            torch.pi
            / (2.0 * num_time_steps)
            * (2.0 * time_step_index + 1.0)
            * basis_coefficient_index
        )

In [49]:
dct_basis_function_matrix.repeat(1, 2).shape

torch.Size([5, 8])

In [41]:
t = 3
pos = torch.tensor([0.5, 0.5, 0.5])[None, ...]
linear_layer_output = torch.randn([3, num_basis_coefficients])
linear_layer_output

tensor([[ 0.1270,  1.8347,  0.7564,  0.9836],
        [ 0.1931, -0.4562, -0.0228, -0.9139],
        [-0.9598,  0.4207,  0.9171, -0.4814]])

In [42]:
dct_basis_function_matrix[t-1]

tensor([ 6.3246e-01, -2.7646e-08, -6.3246e-01,  7.5420e-09])

In [43]:
linear_layer_output[0]

tensor([0.1270, 1.8347, 0.7564, 0.9836])

In [45]:
output_x = torch.sum(dct_basis_function_matrix[t-1] * linear_layer_output[0])
output_x

tensor(-0.3980)

In [37]:
ideal_output = torch.linalg.solve(dct_basis_function_matrix[t-1][None, ...], pos)

RuntimeError: linalg.solve: A must be batches of square matrices, but they are 1 by 4 matrices